tasks:
  - before: |
      echo $GPG_KEY | base64 -d | gpg --import --pinentry=loopback --passphrase "$GPG_PASSPHRASE"
      echo 'pinentry-mode loopback' >> ~/.gnupg/gpg.conf
  - init: |
      pip install poetry
      poetry config virtualenvs.create false
      poetry install
  - command: |
  
vscode:
  extensions:
    - ms-python.python
    - matangover.mypy
ports:
  - port: 8000
    visibility: public
    onOpen: ignore