name: Flake8

on:
  pull_request:
  workflow_dispatch:

jobs:
  code_styling:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install flake8
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install
      - name: Run Black
        run: black homeassistant_api --check
      - name: Run iSort
        run: isort homeassistant_api --check-only
      - name: Run Flake8
        run: flake8 homeasistant_api
      - name: Run MyPy
        run: mypy homeasistant_api --show-error-codes
      - name: Runn PyLint
        run: pylint homeasistant_api
